// <auto-generated />
using System;
using GameStats.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStats.Data.Migrations
{
    [DbContext(typeof(GameStatsDbContext))]
    [Migration("20251016131826_0.04")]
    partial class _004
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameStats.Data.Entities.CODE_VALUE", b =>
                {
                    b.Property<int>("CODE_TABLE_ID")
                        .HasColumnType("int");

                    b.Property<int>("CODE_VALUE_ID")
                        .HasColumnType("int");

                    b.Property<string>("DECODE_TXT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EXTRA_INFO")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CODE_TABLE_ID");

                    b.ToTable("CODE_VALUE");
                });

            modelBuilder.Entity("GameStats.Data.Entities.GAME", b =>
                {
                    b.Property<int>("GAME_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GAME_ID"));

                    b.Property<string>("GAME_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("GAME_ID");

                    b.ToTable("GAME");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MAP", b =>
                {
                    b.Property<int>("MAP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MAP_ID"));

                    b.Property<int>("GAME_ID")
                        .HasColumnType("int");

                    b.Property<string>("MAP_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MAP_ID");

                    b.HasIndex("GAME_ID");

                    b.ToTable("MAP");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH", b =>
                {
                    b.Property<int>("MATCH_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MATCH_ID"));

                    b.Property<DateTime?>("CREATED_DATE")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GAME_ID")
                        .HasColumnType("int");

                    b.Property<int>("MAP_ID")
                        .HasColumnType("int");

                    b.Property<int>("MATCH_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int?>("MATCH_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<int>("OLD_MATCH_ID")
                        .HasColumnType("int");

                    b.Property<int?>("TOTAL_TIME")
                        .HasColumnType("int");

                    b.Property<int>("TYPE_CD")
                        .HasColumnType("int");

                    b.HasKey("MATCH_ID");

                    b.HasIndex("GAME_ID");

                    b.HasIndex("MAP_ID");

                    b.HasIndex("MATCH_TYPE_ID");

                    b.ToTable("MATCH");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH_PLAYER", b =>
                {
                    b.Property<int>("MATCH_PLAYER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MATCH_PLAYER_ID"));

                    b.Property<int>("MATCH_ID")
                        .HasColumnType("int");

                    b.Property<int?>("MATCH_TEAM_ID")
                        .HasColumnType("int");

                    b.Property<int>("PLAYER_ID")
                        .HasColumnType("int");

                    b.Property<int>("SCORE")
                        .HasColumnType("int");

                    b.HasKey("MATCH_PLAYER_ID");

                    b.HasIndex("MATCH_ID");

                    b.HasIndex("MATCH_TEAM_ID");

                    b.HasIndex("PLAYER_ID");

                    b.ToTable("MATCH_PLAYER");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH_TEAM", b =>
                {
                    b.Property<int>("MATCH_TEAM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MATCH_TEAM_ID"));

                    b.Property<int>("MATCH_ID")
                        .HasColumnType("int");

                    b.Property<int>("TEAM_COLOR")
                        .HasColumnType("int");

                    b.HasKey("MATCH_TEAM_ID");

                    b.HasIndex("MATCH_ID");

                    b.ToTable("MATCH_TEAM");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH_TYPE", b =>
                {
                    b.Property<int>("MATCH_TYPE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MATCH_TYPE_ID"));

                    b.Property<int>("GAME_ID")
                        .HasColumnType("int");

                    b.Property<string>("MATCH_TYPE_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MATCH_TYPE_ID");

                    b.HasIndex("GAME_ID");

                    b.ToTable("MATCH_TYPE");
                });

            modelBuilder.Entity("GameStats.Data.Entities.PLAYER", b =>
                {
                    b.Property<int>("PLAYER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PLAYER_ID"));

                    b.Property<string>("EMBLEM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GAME_ID")
                        .HasColumnType("int");

                    b.Property<string>("PLAYER_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PLAYER_ID");

                    b.HasIndex("GAME_ID");

                    b.ToTable("PLAYER");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MAP", b =>
                {
                    b.HasOne("GameStats.Data.Entities.GAME", "GAME")
                        .WithMany("MAPS")
                        .HasForeignKey("GAME_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GAME");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH", b =>
                {
                    b.HasOne("GameStats.Data.Entities.GAME", "GAME")
                        .WithMany("MATCHES")
                        .HasForeignKey("GAME_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStats.Data.Entities.MAP", "MAP")
                        .WithMany("MATCHES")
                        .HasForeignKey("MAP_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStats.Data.Entities.MATCH_TYPE", "MATCH_TYPE")
                        .WithMany("MATCHES")
                        .HasForeignKey("MATCH_TYPE_ID");

                    b.Navigation("GAME");

                    b.Navigation("MAP");

                    b.Navigation("MATCH_TYPE");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH_PLAYER", b =>
                {
                    b.HasOne("GameStats.Data.Entities.MATCH", "MATCH")
                        .WithMany("MATCH_PLAYER")
                        .HasForeignKey("MATCH_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStats.Data.Entities.MATCH_TEAM", "MATCH_TEAM")
                        .WithMany("MATCH_PLAYERS")
                        .HasForeignKey("MATCH_TEAM_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameStats.Data.Entities.PLAYER", "PLAYER")
                        .WithMany("MATCH_PLAYERS")
                        .HasForeignKey("PLAYER_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MATCH");

                    b.Navigation("MATCH_TEAM");

                    b.Navigation("PLAYER");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH_TEAM", b =>
                {
                    b.HasOne("GameStats.Data.Entities.MATCH", "MATCH")
                        .WithMany("MATCH_TEAM")
                        .HasForeignKey("MATCH_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MATCH");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH_TYPE", b =>
                {
                    b.HasOne("GameStats.Data.Entities.GAME", "GAME")
                        .WithMany("MATCH_TYPES")
                        .HasForeignKey("GAME_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GAME");
                });

            modelBuilder.Entity("GameStats.Data.Entities.PLAYER", b =>
                {
                    b.HasOne("GameStats.Data.Entities.GAME", "GAME")
                        .WithMany("PLAYERS")
                        .HasForeignKey("GAME_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GAME");
                });

            modelBuilder.Entity("GameStats.Data.Entities.GAME", b =>
                {
                    b.Navigation("MAPS");

                    b.Navigation("MATCHES");

                    b.Navigation("MATCH_TYPES");

                    b.Navigation("PLAYERS");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MAP", b =>
                {
                    b.Navigation("MATCHES");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH", b =>
                {
                    b.Navigation("MATCH_PLAYER");

                    b.Navigation("MATCH_TEAM");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH_TEAM", b =>
                {
                    b.Navigation("MATCH_PLAYERS");
                });

            modelBuilder.Entity("GameStats.Data.Entities.MATCH_TYPE", b =>
                {
                    b.Navigation("MATCHES");
                });

            modelBuilder.Entity("GameStats.Data.Entities.PLAYER", b =>
                {
                    b.Navigation("MATCH_PLAYERS");
                });
#pragma warning restore 612, 618
        }
    }
}
